numbers = [45, 12, 78, 34, 89, 23]
print("Student: Deepak")
print("Length:", len(numbers))
print("Maximum:", max(numbers))
print("Minimum:", min(numbers))
print("Sum:", sum(numbers))
print("Sorted:", sorted(numbers))
print("Student: Nandini")
print("Absolute value of -9:", abs(-9))
print("Power 2^8:", pow(2, 8))
print("Round 3.7654:", round(3.7654, 2))
name = "nandini"
print("Upper:", name.upper())
print("Length of name:", len(name))
print("Student: Aarti")
print("Type of 10:", type(10))
print("Type of 3.14:", type(3.14))
print("Type of 'Hello':", type("Hello"))
print("int('42'):", int("42"))
print("float('3.14'):", float("3.14"))
print("str(100):", str(100))
print("bool(0):", bool(0))
print("bool(1):", bool(1))
